import About from '@/comp/about/About'
import Head from 'next/head'
import React from 'react'

const about = () => {
  return (
    <div>
        <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About/>
    </div>
  )
}

export default about
