import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import About from '@/comp/about/About'
import Contact from '@/comp/about/Contact'
import Component from '@/pages/login'
import login from "./login";
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main style={{display:"flex", justifyContent:"center", flexDirection:"column", alignItems:"center"}}>
     <h1>Auth testing</h1>
     <h2>You are at the home page </h2>
     <img style={{height:"400px" , width:"400px"}} src={props.res.message} alt="dog-ceo" />
     
     <br />
    <Link style={{padding:"1rem"}} href='./login'><button style={{padding:".6rem" ,fontSize:"1.2rem"}}> Login Page </button></Link>
    <Link href='./account'><button style={{padding:".6rem", fontSize:"1.2rem"}}>account page </button></Link>
     </main>
    </>
  )
}

export const getServerSideProps = async (context) =>{
  const data = await fetch ('https://dog.ceo/api/breeds/image/random');
const res= await data.json();
console.log(res);
return {
  props:{res}
}
}