import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import About from '@/comp/about/About'
import Contact from '@/comp/about/Contact'
import Component from '@/pages/login'
import login from "./login";
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
     <h1>Auth testing</h1>
     <h2>You are at the home page </h2>
     
     <br />
    <Link href='./login'><button> Login Page </button></Link>
    <Link href='./account'><button>account </button></Link>
     </main>
    </>
  )
}
